### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by pcraston** [saippuakauppias/django-maven#5]
I can't get this to work with Django 1.8. It throws a "no such option --settings" error.

Any ideas?

**Comment by skorokithakis** [comment]
I'm getting this:

```
./manage.py maven autobill --days=10

Traceback (most recent call last):
  File "/repo/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/repo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/repo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/repo/env/local/lib/python2.7/site-packages/django_maven/management/commands/maven.py", line 54, in run_from_argv
    options = parser.parse_args(argv[3:])
  File "/repo/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 64, in parse_args
    return super(CommandParser, self).parse_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1691, in parse_args
    self.error(msg % ' '.join(argv))
  File "/repo/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 70, in error
    raise CommandError("Error: %s" % message)
django.core.management.base.CommandError: Error: unrecognized arguments: --days=10
```

**Comment by Sinkler** [comment]
i have the same error
